In [1]:
import pandas as pd

In [3]:
%pwd

'/home/user/Documents/ML DL PROJECTS/IMDBMovieReviewSentimentAnalysis/notebooks'

In [5]:
import os

In [6]:
os.chdir('../')

In [7]:
%pwd

'/home/user/Documents/ML DL PROJECTS/IMDBMovieReviewSentimentAnalysis'

In [8]:
df = pd.read_csv('datasets/IMDB Dataset.csv')

In [9]:
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [10]:
df['review'] = df['review'].str.lower()

In [11]:
import re
def remove_html_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'', text)

In [12]:
 df['review'] = df['review'].apply(remove_html_tags)

In [13]:
def remove_url(text):
  pattern = re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'', text)

In [16]:
def remove_punc(text):
  return text.translate(str.maketrans('','',exclude))

In [18]:
import string

In [19]:
exclude = string.punctuation

In [20]:
df['review'] = df['review'].apply(remove_punc)

In [23]:
from textblob import TextBlob

In [24]:
def remove_stopwords(text):
  new_text = ""
  for word in text.split():
    if  word.lower() not in stopwords:
      new_text += word
      new_text += ' '
  return new_text

In [27]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/user/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [28]:
stopwords = stopwords.words('english')

In [29]:
df['review'] = df['review'].apply(remove_stopwords)

In [32]:
def correct_text(text):
    txtblb = TextBlob(text)
    return txtblb.correct().string

In [34]:
# df['review'] = df['review'].apply(correct_text)

In [35]:
df.head()

                                              review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production filming technique ...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically theres family little boy jake thinks...  negative
4  petter matteis love time money visually stunni...  positive

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
le = LabelEncoder()

In [39]:
df['sentiment'] = le.fit_transform(df['sentiment'])

In [40]:
df.head()

                                              review  sentiment
0  one reviewers mentioned watching 1 oz episode ...          1
1  wonderful little production filming technique ...          1
2  thought wonderful way spend time hot summer we...          1
3  basically theres family little boy jake thinks...          0
4  petter matteis love time money visually stunni...          1

In [41]:
def remove_numbers(text):
  pattern = re.compile(r'\d+')
  return pattern.sub(r'', text).strip()

In [42]:
df['review'] = df['review'].apply(remove_numbers)

In [43]:
df.head()

                                              review  sentiment
0  one reviewers mentioned watching  oz episode y...          1
1  wonderful little production filming technique ...          1
2  thought wonderful way spend time hot summer we...          1
3  basically theres family little boy jake thinks...          0
4  petter matteis love time money visually stunni...          1

In [1]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<nothing>')

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
def text_to_sequences(text):
    return tokenizer.texts_to_sequences([text])